-- MySQL Script generated by MySQL Workbench
-- Wed Jun  7 11:00:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema livraria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema livraria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `livraria` DEFAULT CHARACTER SET utf8 ;
USE `livraria` ;

insert into editora values ('Globo',123);
insert into livro values (1,'Nárnia',1990,35.5,123);

select * from livro;

-- -----------------------------------------------------
-- Table `livraria`.`Editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livraria`.`Editora` (
  `Nome` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`CNPJ`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `livraria`.`Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livraria`.`Livro` (
  `idLivro` INT NOT NULL,
  `Título` VARCHAR(45) NOT NULL,
  `AnoPubli` VARCHAR(45) NOT NULL,
  `Preco` DOUBLE NOT NULL,
  `Editora_CNPJ` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idLivro`),
  INDEX `fk_Livro_Editora1_idx` (`Editora_CNPJ` ASC) VISIBLE,
  CONSTRAINT `fk_Livro_Editora1`
    FOREIGN KEY (`Editora_CNPJ`)
    REFERENCES `livraria`.`Editora` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `livraria`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livraria`.`Cliente` (
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(15) NOT NULL,
  `Telefone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livraria`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livraria`.`Pedido` (
  `idPedido` INT NOT NULL,
  `dataPedido` DATE NOT NULL,
  `statusPedido` VARCHAR(45) NOT NULL,
  `Cliente_CPF` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_CPF`)
    REFERENCES `livraria`.`Cliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livraria`.`Pedido_has_Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livraria`.`Pedido_has_Livro` (
  `Pedido_idPedido` INT NOT NULL,
  `Livro_idLivro` INT NOT NULL,
  PRIMARY KEY (`Pedido_idPedido`, `Livro_idLivro`),
  INDEX `fk_Pedido_has_Livro_Livro1_idx` (`Livro_idLivro` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Livro_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Livro_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `livraria`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Livro_Livro1`
    FOREIGN KEY (`Livro_idLivro`)
    REFERENCES `livraria`.`Livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
